# Generated by Django 3.2.20 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRegister',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('busname', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=25)),
                ('starting_point', models.CharField(max_length=25)),
                ('destination_point', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bus_register',
                'managed': False,
            },
        ),
    ]
