# Generated by Django 3.2.20 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('realtime_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_id', models.IntegerField()),
                ('route_id', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('speed', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'realtime',
                'managed': False,
            },
        ),
    ]
