# Generated by Django 3.2.20 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('end_stop_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bus_route',
                'managed': False,
            },
        ),
    ]
