# Generated by Django 3.2.20 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
    ]
