# Generated by Django 3.2.20 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favourite',
                'managed': False,
            },
        ),
    ]
