# Generated by Django 3.2.20 on 2024-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('attractions_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'attractions',
                'managed': False,
            },
        ),
    ]
